"""add user password_hash and test_case metadata fields

Revision ID: 3be6f28452de
Revises: 69d178bd2aee
Create Date: 2026-09-21 19:39:59.611286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be6f28452de'
down_revision: Union[str, None] = '69d178bd2aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('objective', sa.Text(), nullable=True))
    op.add_column('test_cases', sa.Column('scenario_category', sa.String(length=100), nullable=True))
    op.add_column('test_cases', sa.Column('pass_criteria', sa.Text(), nullable=True))
    op.add_column('test_cases', sa.Column('fail_criteria', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_column('test_cases', 'fail_criteria')
    op.drop_column('test_cases', 'pass_criteria')
    op.drop_column('test_cases', 'scenario_category')
    op.drop_column('test_cases', 'objective')
    # ### end Alembic commands ###
