"""add extracted_segments table

Revision ID: 9533c7253dd9
Revises: 79ff67caa98a
Create Date: 2026-09-17 19:35:50.514848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9533c7253dd9'
down_revision: Union[str, None] = '79ff67caa98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_version_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=500), nullable=True),
    sa.Column('segment_type', sa.Enum('TEXT', 'TABLE', name='segmenttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracted_segments')
    # ### end Alembic commands ###
