"""add test_case invalid_condition field

Revision ID: fa6cd1756e8a
Revises: 3be6f28452de
Create Date: 2026-09-21 19:43:13.342392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6cd1756e8a'
down_revision: Union[str, None] = '3be6f28452de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('invalid_condition', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'invalid_condition')
    # ### end Alembic commands ###
